# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

client:
  connect_to:
    host: 10.10.1.2
    port: 3000
  client:
    host: 10.10.1.1
    port: 3000
server:
  bind:
    host: 10.10.1.2
    port: 3000
  client:
    host: 10.10.1.1
    port: 3000
catnip:
  my_ipv4_addr: 10.10.1.2
  my_link_addr: "9c:dc:71:5d:f5:a1"
  my_interface_name: "ens1f1"
  arp_table:
    "9c:dc:71:5d:f5:a1": "10.10.1.2"
    "9c:dc:71:5d:01:91": "10.10.1.1"
dpdk:
  eal_init: ["-c", "0xff", "-n", "4", "-w", "03:00.1","--proc-type=auto"]
